selmag:
  services:
    catalogue:
      uri: http://localhost:8081
      username: catalogue_service_user
      password: '{noop}password'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/manager
    username: manager
    password: manager
  flyway:
    schemas:
      - public
      - manager
  jpa:
    show-sql: true